language: bash
sudo: required
git:
  depth: 1

# Set a supported language, otherwise the Windows worker will not start.
os: osx
        
before_install:
  - echo $TRAVIS_OS_NAME
  - wget https://drive.google.com/uc?authuser=0&id=1Jzn4COqKBaIIDTkJyB2KHfJ9yZAhpeqU&export=download -O ~/512_release_static.tar.gz
  - mkdir ~/Qt
  - tar xz ~/512_release_static.tar.gz -C ~/Qt
  - cd ~/Qt && ls
  - du -sh .
  - export PATH=$PATH:~/Qt/512_release_static/bin
after_script:
  - which qmake
