language: shell
git:
  depth: 1

# Set a supported language, otherwise the Windows worker will not start.
os: windows
        
before_install:
  - echo $TRAVIS_OS_NAME
  # windows
  - curl -vLo ~/qt-opensource-windows-x86-5.12.0.exe http://download.qt.io/official_releases/qt/5.12/5.12.0/qt-opensource-windows-x86-5.12.0.exe
  - ~/qt-opensource-windows-x86-5.12.0.exe --script qt-installer-windows.qs
after_script:
  - qmake --version
