language: c
git:
  depth: 1

# Set a supported language, otherwise the Windows worker will not start.
os: windows
        
before_install:
  - echo $TRAVIS_OS_NAME
  # windows
  - curl -vLo ~/qt-unified-windows-x86-online.exe http://download.qt.io/official_releases/online_installers/qt-unified-windows-x86-online.exe
  - ~/qt-unified-windows-x86-online.exe --verbose --script qt-installer-windows.qs
after_script:
  - qmake --version
